version: "2"

services:
  web:
    build:
      context: ./web/
      dockerfile: Dockerfile
    env_file: .env
    links:
      - redis
      - db
    ports:
      - "${EXTERNAL_PORT}:5000"
    volumes:
      - ./persists:/persists
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://postgres@db/postgres
      - FLASK_CONFIG=production
      - REDISTOGO_URL=redis://redis:6379
      - DATABASE_HOST=db


  db:
    image: postgres:latest
    env_file: .env
    environment:
      - POSTGRES_USER=postgres
    volumes:
      - ./data:/var/lib/postgresql/data


  redis:
    image: redis:latest
    env_file: .env
    volumes:
      - ./redis:/var/lib/redis
